name: ci

on: [push, pull_request]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.2.2

      - name: Run fmt --check
        run: deno fmt --check

      - name: Run lint
        run: deno lint --unstable
